import os
import subprocess
import shutil
import torchaudio

# ==========================================
# Configuration
# ==========================================
# htdemucs: Hybrid Transformer Demucs (Meta's latest & best model)
# v4: Optimized for both quality and speed
MODEL_NAME = "htdemucs"


def separate_audio(file_path, output_dir="temp_stems"):
    """
    Separates audio using Meta's Demucs (SOTA) via subprocess.
    """
    filename = os.path.basename(file_path)
    print(f"🔪 Separating Stems (High Quality - Demucs): {filename}...")

    # 1. Clean previous results if any
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir, exist_ok=True)

    # 2. Construct Command
    # demucs -n htdemucs --out [output_dir] [input_file] --device cpu
    # We force CPU usage for stability on Mac (OOM prevention)
    cmd = [
        "demucs",
        "-n", MODEL_NAME,
        "--out", output_dir,
        "--device", "cpu",
        file_path
    ]

    print("⏳ Running Demucs... (This will take 3-5 mins for High Quality)")

    try:
        # Run the command and wait for it to finish
        subprocess.run(cmd, check=True)
        # print(result.stdout.decode()) # Uncomment for debug
    except subprocess.CalledProcessError as e:
        print(f"❌ Demucs Error: {e.stderr.decode()}")
        return {}

    # 3. Locate and Move Files
    # Demucs saves to: output_dir/htdemucs/song_name/vocals.wav
    # We want to move them to: output_dir/vocals.wav

    # Filename without extension (Demucs creates a folder with this name)
    song_name_no_ext = os.path.splitext(filename)[0]
    demucs_output_folder = os.path.join(output_dir, MODEL_NAME, song_name_no_ext)

    saved_paths = {}
    target_names = ['vocals', 'drums', 'bass', 'other']

    if not os.path.exists(demucs_output_folder):
        print(f"❌ Could not find output folder: {demucs_output_folder}")
        return {}

    for target in target_names:
        src_path = os.path.join(demucs_output_folder, f"{target}.wav")
        dst_path = os.path.join(output_dir, f"{target}.wav")

        if os.path.exists(src_path):
            # Move file to main output directory
            shutil.move(src_path, dst_path)
            saved_paths[target] = dst_path
            print(f"   ✅ Saved: {target}.wav")

    # Cleanup empty folders generated by Demucs
    try:
        shutil.rmtree(os.path.join(output_dir, MODEL_NAME))
    except:
        pass

    return saved_paths


if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)
    test_song = os.path.join(project_root, "data", "my_songs", "9624 JAZZ CLUB AR.wav")

    if os.path.exists(test_song):
        separate_audio(test_song, output_dir=os.path.join(project_root, "results", "stems"))
    else:
        print(f"❌ Test song not found at: {test_song}")